version: "3.7"

services:
  db:
    image: mysql:latest
    container_name: mysql_db_finalProject
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: repaircomputer_db
    ports:
      - "8006:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_finalProject
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - my_network

  app:  # แก้ไขให้ใช้ชื่อ service ที่ถูกต้อง เช่น 'app'
    image: node:latest  # ใช้ Node.js Docker Image ล่าสุด
    container_name: node_app_finalProject
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app  # Mount ไฟล์ทั้งหมดในโฟลเดอร์ปัจจุบันไปยัง container
    command: npm run dev  # รันคำสั่ง npm
    ports:
      - "8000:8000"  # เปิดพอร์ตสำหรับ Node.js (ปรับตามแอปของคุณ)
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
