version: "3.7"

services:
db:
  image: mysql:5.7
  container_name: mysql_db_finalProject
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: repaircomputer_db
    # ตั้งค่าให้ MySQL ใช้ utf8mb4
    MYSQL_CHARSET: utf8mb4
  ports:
    - "8006:3306"
  volumes:
    - mysql_data:/var/lib/mysql
  networks:
    - my_network
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_finalProject
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - my_network

  app:
    build:
      context: .  # บอกให้ใช้ Dockerfile จากโฟลเดอร์ปัจจุบัน
    container_name: node_app_finalProject
    volumes:
      - .:/usr/src/app  # Mount ไฟล์ทั้งหมดในโฟลเดอร์ปัจจุบันไปยัง container
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local